### ISSUE TITLE
weird logs, is this mean got bypassed?

### ISSUE THREAD

**Issue by fakgayhub** [41Baloo/balooProxy#61]
![1223d23d23](https://github.com/user-attachments/assets/c8016891-6203-419b-8f0b-75fcfce8b263)

I dont know what does it mean

And why it keeps on stage 1?

**Comment by 41Baloo** [comment]
UNK followed by the hex numbers means they have a tls fingerprint (the hex numbers) not yet known to BalooProxy

**Comment by libalpm64** [comment]
The log shows only bypassed requests The fingerprint, like Baloo said, is followed by the end if unidentified. It keeps it on stage one because your config.json has the "bypassStage1":yournumbergoeshere edit this parameter in the config.json to make it switch to the next stage based on the number of requests per second then restart your program.
